actions:
  install_dein: ~/dotfiles/setup_scripts/install_dein.sh
  run_dein: nvim "+call dein#install()" "+qall"
config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_bin:
    dst: ~/bin
    src: bin
  d_nvim:
    dst: ~/.config/nvim
    src: config/nvim
    actions:
      - install_dein
      - run_dein
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
profiles:
  macbook:
    dotfiles:
    - f_tmux.conf
    - d_nvim
    - d_bin
  personal_desktop:
    dotfiles:
    - f_tmux.conf
    - d_nvim
    - d_bin
