config:
  backup: true
  create: true
  dotpath: dotfiles
dotfiles:
  d_nvim:
    dst: ~/.config/nvim
    src: config/nvim
  f_tmux.conf:
    dst: ~/.tmux.conf
    src: tmux.conf
profiles:
  macbook:
    dotfiles:
    - f_tmux.conf
    - d_nvim
